---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${application.name}
    namespace: ${openshift.namespace}
    labels:
      app: ${application.name}
      provider: fabric8
      project: ${application.name}
      version: ${project.version}
      group: ${project.groupId}
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${application.name}
    namespace: ${openshift.namespace}
    labels:
      app: ${application.name}
      provider: fabric8
      project: ${application.name}
      version: ${project.version}
      group: ${project.groupId}
  spec:
    runPolicy: Serial
    source:
      type: Git
      git:
        uri: '${project.scm.url}'
        ref: master
    strategy:
      type: Docker
      dockerStrategy:
        dockerfilePath: src/main/docker/Dockerfile
    output:
      to:
        kind: ImageStreamTag
        name: '${application.name}:latest'
    resources: {}
    postCommit: {}
    nodeSelector: null
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${application.name}
    namespace: ${openshift.namespace}
    labels:
      app: ${application.name}
      provider: fabric8
      project: ${application.name}
      version: ${project.version}
      group: ${project.groupId}
  spec:
    replicas: 1
    strategy:
      type: Rolling
      rollingParams:
        updatePeriodSeconds: 1
        intervalSeconds: 1
        timeoutSeconds: 600
        maxUnavailable: 25%
        maxSurge: 25%
      resources: {}
    selector:
      project: ${application.name}
      provider: fabric8
      version: ${project.version}
      group: ${project.groupId}
    template:
      metadata:
        labels:
          app: ${application.name}
          provider: fabric8
          project: ${application.name}
          version: ${project.version}
          group: ${project.groupId}
      spec:
        containers:
        - name: ${application.name}
          imagePullPolicy: IfNotPresent
          env:
          - name: SPRING_PROFILES_ACTIVE
            value: in_memory
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          securityContext:
            privileged: false
          volumeMounts:
          - name: tomcat-logs
            mountPath: /opt/tomcat/logs
          - name: tomcat-work
            mountPath: /opt/tomcat/work
          - name: tomcat-temp
            mountPath: /opt/tomcat/temp
        volumes:
        - name: tomcat-logs
          emptyDir: {}
        - name: tomcat-work
          emptyDir: {}
        - name: tomcat-temp
          emptyDir: {}
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - ${application.name}
        from:
          kind: ImageStreamTag
          namespace: ${openshift.namespace}
          name: ${application.name}:latest
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    name: ${application.name}-service
    namespace: ${openshift.namespace}
    annotations:
      prometheus.io/port: "9779"
      prometheus.io/scrape: "true"
    labels:
      expose: "true"
      app: ${application.name}
      provider: fabric8
      project: ${application.name}
      version: ${project.version}
      group: ${project.groupId}
  spec:
    ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
    - name: 8778-tcp
      protocol: TCP
      port: 8778
      targetPort: 8778
    selector:
      project: ${application.name}
      provider: fabric8
      group: ${project.groupId}
    type: ClusterIP
    sessionAffinity: None
- apiVersion: v1
  kind: Route
  metadata:
    name: ${application.name}-service
    namespace: ${openshift.namespace}
    labels:
      expose: "true"
      provider: fabric8
      project: ${application.name}
      version: ${project.version}
      group: ${project.groupId}
  spec:
    host: ${application.name}.${openshift.domain}
    to:
      kind: Service
      name: ${application.name}-service
      weight: 100
    port:
      targetPort: 8080-tcp
    wildcardPolicy: None